---
title: "PCAInRExample"
author: "Dr. B"
date: "Friday, October 31, 2014"
output: html_document
---

```{r}
##Use my standard openning including call function
source('C:/Users/bryan_000/Documents/GitHub/MyWork/StdOpen.R')

call("FactoMineR")

#Set name of datafile
datafile=paste(datadir,"pca_gsp.csv",sep = "")

##Get the Data
mydata<- read.csv(datafile)
```


```{r}
# Define variables
X <- cbind(mydata$Ag, mydata$Mining, mydata$Constr, mydata$Manuf, mydata$Manuf_nd, mydata$Transp, mydata$Comm, mydata$Energy, mydata$TradeW, mydata$TradeR, mydata$RE, mydata$Services, mydata$Govt)

# Descriptive statistics
summary(X)
cor(X)
```


```{r}
# Principal component analysis using correlation
pca1 <- princomp(X, scores=TRUE, cor=TRUE)
summary(pca1)

# Loadings of principal components
loadings(pca1)
#pca1$loadings

# Scores of the components, 
pca1$scores[1:10,]
```


```{r}
# Principal component analysis using covar
pca2 <- princomp(X, scores=TRUE, cor=FALSE)
summary(pca2)

# Loadings of principal components
loadings(pca2)
#pca2$loadings

# Scores of the components, 
pca2$scores[1:10,]
```


```{r}
# Scree plot of eigenvalues
plot(pca1, type="line", main="Scree Plot by Cor")
plot(pca2, type="line", main="Scree Plot by Cov")

#Can use the following to get same screeplot
#screeplot(pca1, type="line", main="Scree Plot 2")
```


```{r}
# Biplot of score variables
biplot(pca1,main="biplot by Cor")
abline(v=0)
abline(h=0)
biplot(pca2,main="biplot by Cov")
abline(v=0)
abline(h=0)
```


```{r}
##PCA Another way
pca3 <- PCA(X)
dimdesc(pca3)
```


```{r}

```


```{r}

```