---
title: "RandomForest"
author: "Dr. B"
date: "Sunday, November 23, 2014"
output: html_document
---

```{r}
rm(list=ls())
library(AppliedPredictiveModeling)
library(caret)
library(e1071)
library(randomForest)
library(knitr)
data(concrete) 

inTrain = createDataPartition(concrete$CompressiveStrength, p = 3/4)[[1]]
training = concrete[ inTrain,]
testing = concrete[-inTrain,]

##Apply the Random Forest

##fit the randomforest model
model <- randomForest(CompressiveStrength~.,data = training,importance=TRUE,keep.forest=TRUE)
predict(model, newdata=testing[ ,-9])
varImpPlot(model, type=1)
 
##what is the proportion variation explained in the outcome of the testing data?
##i.e., what is 1-(SSerror/SStotal)
#actual <- testing$CompressiveStrength
#rsq <- 1-sum((actual-predicted)^2)/sum((actual-mean(actual))^2)
#print(rsq)

##
tg = data.frame(fraction = (1:99)/100)
model = train(CompressiveStrength ~ ., data = training, method = "lasso", tuneGrid = tg)
resultslasso <- data.frame(model$results)
plot(model$finalModel, xvar = "penalty", use.color = T)
pred.2 <- predict(model, testing)

##SVM Model (need library e071)
model = svm(CompressiveStrength ~ ., data = training)
resultssvm <- data.frame(model$results)
pred.3 <- predict(model, testing) 

##RF
##Set the training control
ctrl <- trainControl(method = "cv", number = 5, allowParallel = TRUE)
model = train(CompressiveStrength ~ ., data = training, method = "rf", ntree = 200, trControl = ctrl)
resultsrf <- data.frame(model$results)
pred.4 <- predict(model,testing)

##k-nearest neighbors
model <- train(CompressiveStrength ~ ., training, method = "knn", trControl = ctrl)
resultsknn <- data.frame(model$results)
pred.5 <- predict(model, testing)

##Decision Tree
model<- train(CompressiveStrength ~ ., training, method="ctree", trControl = ctrl)
resultsdt <- data.frame(model$results)
pred.6 <- predict(model,testing)

par(mfrow = c(1,2))
hist(pred.2, col="yellow", border="red")
hist(pred.3, col="lightblue", border="red")
hist(pred.4, col="green", border="red")
hist(pred.5, col="red", border="black")
hist(pred.6, col="blue", border="red")
