---
title: "R Commands"
author: "Dr. B"
date: "Sunday, September 14, 2014"
output: html_document
---

----------
First, need to generate some random data
```{r}
# Generate some random data
x = rnorm(263,25,5)
y = rnorm(263,20,7)
```

Load needed librarys
```{r}
if (!require("e1071")) {
  install.packages("e1071")
}
```

Stats One numberical value
```{r}
summary(x) # most summary statitstics at once
mean(x) # na.rm = TRUE to get rid of NA values
median(x) # na.rm = TRUEto get rid of NA values
sd(x)# na.rm = TRUE to get rid of NA values'
range(x)
quantile(x)
quantile(x, c(.32, .57, .98)) #quantile(duration, c(.32, .57, .98)) 
IQR(x)   # apply the IQR function
skewness(x)
kurtosis(x)  
mad(x)    #(median absolute deviation)
max(x)
min(x)
sum(x)
var(x)     #produces the variance covariance matrix
```

Stats Two numberical value
```{r}
cor(x,y,use="pair") #correlation matrix for pairwise complete data, use="complete" for complete cases
cor.test(x,y)
```

Graphs, one numerical value
```{r}
stem(x)
hist(x)
boxplot(x) # horizontal = TRUE for horizontal plot
qqnorm(x)
qqline(x) # for normal probability plot and straight line
```

Sample 
```{r}
# sample from x size number of elements without replacement (default)
# to sample with replacement replace = TRUE
sample(x, 30, replace = FALSE)
```

One Categorical Variable
------------------------
Generate categorical data
```{r}
maj <-c(rep("science",81),rep("social science",129),rep("arts",53))
ses <-c(rep("low",48),rep("lower middle",58),rep("upper middle",80),rep("upper",77))
```

Table
```{r}
table(maj)
table(ses)
```

Visualize 
```{r}
barplot(table(ses))
```

Two Categorical Variables
--------------------------
```{r}
table(maj,ses)
```

```{r}
barplot(table(maj,ses)) # beside = TRUE for side-by-side barplot # legend = TRUE to include a color legend 
mosaicplot(table(maj,ses))
```

One quantative and one categorical Variable
-------------------------------------------
```{r}
by(x, maj, summary) # summary by group
by(x, maj, mean) # mean by group
# na.rm = TRUE to get rid of NA values
by(x, maj, sd) # sd by group na.rm = TRUE to get rid of NA values
```

Visualization with horizental line at mean
```{r}
boxplot(x ~ maj)
abline(h=mean(x, na.rm="True"), col="Red")
```

Histogram of x
```{r}
hist(x)
```

Add a rug to a histogram
```{r}
hist(x)
rug(x)
```

Add a vertical line at the mean
```{r}
hist(x)
abline(v=mean(x, na.rm="True"), col="Red")
rug(x)
```

Useful Functions
```{r}
length(x) # number of elements or components
str(x)    # structure of an object 
class(x)  # class or type of an object (numeric, matrix, data frame, etc)
names(x)  # list the variable names in a data frame
dim(ses)    # number of rows and columns in a data frame
ls()      # list objects in the working environment
rm(z)         #remove Z from the workspace
#rm(list=ls()) #remove all the variables from the workspace
attach(mtcars)     #make the names of the variables in the matrix or data frame available in the workspace
detach(mtcars)     #releases the names
```
